# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install sshpass
      run: |
        sudo apt-get install -y sshpass
      

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:  
        SSHPASS: ${{ secrets.DROPLET_PASS }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} hostname
        ssh root@${{ secrets.DROPLET_IP }} echo "connected (again)"
